---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-event-redhat-cne-org-v1alpha1-hardwareevent
  failurePolicy: Fail
  name: vhardwareevent.kb.io
  rules:
  - apiGroups:
    - event.redhat-cne.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hardwareevents
  sideEffects: None
